Multi-module support

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,14 +1,11 @@
 #!/usr/bin/env bash
 # bin/compile <build-dir> <cache-dir>
 
-# fail fast
-set -e
-
 # parse args
 BUILD_DIR=$1
 CACHE_DIR=$2
 
-# chdir as maven expects
+# chdir to handle relative paths
 cd $BUILD_DIR
 
 # unpack cache
@@ -37,45 +34,25 @@ EOF
   cat Procfile | sed -u 's/^/       /' 
 fi
 
-# Append a db URL prod parameter to application.conf if it's not already there
-
-if ! grep -q -E '^([^#]*)%prod\.db\.url' conf/application.conf ; then
-    echo "%prod.db.url=\${database.jdbc.url}" >> conf/application.conf
-    echo "-----> No %prod.db.url parameter found in conf/application.conf. Adding parameter:"
-    echo "       %prod.db.url=\${database.jdbc.url}"
-fi
-
-# Append a db driver prod parameter to application.conf if it's not already there
-
-if ! grep -q -E '^([^#]*)%prod\.db\.driver' conf/application.conf ; then
-    echo "%prod.db.driver=org.postgresql.Driver" >> conf/application.conf
-    echo "-----> No %prod.db.driver parameter found in conf/application.conf. Adding parameter:"
-    echo "       %prod.db.driver=org.postgresql.Driver"
-    if [ ! -e lib/postgres* ] ; then 
-        if [ ! -e lib ] ; then
-            mkdir lib
-        fi
-        cp .lib/postgres*.jar lib/.
-        echo "        Added postgres JDBC driver lib to application: `ls lib | grep postgres`"
-    fi
-fi
-
-# Append a hibernate ddl strategy parameter to application.conf if it's not already there
-
-if ! grep -q -E '^([^#]*)%prod\.jpa\.ddl' conf/application.conf ; then
-    echo "%prod.jpa.ddl=update" >> conf/application.conf
-    echo "-----> No %prod.jpa.ddl parameter found in conf/application.conf. Adding parameter:"
-    echo "       %prod.jpa.ddl=update"
-fi
-
+check_build_status()
+{
+  if [ "${PIPESTATUS[*]}" != "0 0" ]; then
+    echo " !     Failed to build Play! application"
+    exit 1
+  fi
+}
 
 # build app
-echo "-----> Resolving dependencies and precompiling play! app..."
-.play/play precompile --deps 2>&1 | sed -u 's/^/       /'
-if [ "${PIPESTATUS[*]}" != "0 0" ]; then
-  echo " !     Failed to build Play app"
-  exit 1
-fi
+echo "-----> Building Play! application..."
+CMD_SUFFIX=" 2>&1" # Redirect error output
+# For each 'play run' command in the Procfile, run 'play dependencies'
+cat $BUILD_DIR/Procfile | while read line; do
+  # Strip the process name and replace 'run' command with 'dependencies' command
+  DEPENDENCIES_CMD=$(echo $line | grep -E -o 'play run .*' | sed 's/play run/.play\/play dependencies/')$CMD_SUFFIX
+  echo "       Resolving dependencies: $DEPENDENCIES_CMD" 
+  eval "$DEPENDENCIES_CMD" | sed -u 's/^/       /'
+  check_build_status
+done
 
 # repack cache
 mkdir -p $CACHE_DIR
